// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxQ0pUThtsbpuYwBDd5JH2KCW6MjXMlm0',
    appId: '1:859386680971:web:bff31237d81911651e668e',
    messagingSenderId: '859386680971',
    projectId: 'bananapeel-891ee',
    authDomain: 'bananapeel-891ee.firebaseapp.com',
    storageBucket: 'bananapeel-891ee.appspot.com',
    measurementId: 'G-P8DC7F557H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr5j-k1o9FZPTfTuz9sR68LTaEmeq90vk',
    appId: '1:859386680971:android:47a2a3a131e2b28f1e668e',
    messagingSenderId: '859386680971',
    projectId: 'bananapeel-891ee',
    storageBucket: 'bananapeel-891ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0HKzHSbLKKdsnUF-PYiU35hQGlxLqJ-A',
    appId: '1:859386680971:ios:686ce9a88b6210b31e668e',
    messagingSenderId: '859386680971',
    projectId: 'bananapeel-891ee',
    storageBucket: 'bananapeel-891ee.appspot.com',
    iosBundleId: 'com.example.bananas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0HKzHSbLKKdsnUF-PYiU35hQGlxLqJ-A',
    appId: '1:859386680971:ios:0774a76e27d721be1e668e',
    messagingSenderId: '859386680971',
    projectId: 'bananapeel-891ee',
    storageBucket: 'bananapeel-891ee.appspot.com',
    iosBundleId: 'com.example.bananas.RunnerTests',
  );
}
